# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_ref_design_system_ila_0_0.xci
# IP: The module: 'bd_ref_design_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/bd_01ee.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_01ee || ORIG_REF_NAME==bd_01ee} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/bd_01ee_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_01ee_ila_lib_0 || ORIG_REF_NAME==bd_01ee_ila_lib_0} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_01ee_ila_lib_0 || ORIG_REF_NAME==bd_01ee_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_01ee_ila_lib_0 || ORIG_REF_NAME==bd_01ee_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/bd_01ee_ila_lib_0_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/bd_01ee_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_ref_design_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_ref_design_system_ila_0_0.xci
# IP: The module: 'bd_ref_design_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/bd_01ee.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_01ee || ORIG_REF_NAME==bd_01ee} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/bd_01ee_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_01ee_ila_lib_0 || ORIG_REF_NAME==bd_01ee_ila_lib_0} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_01ee_ila_lib_0 || ORIG_REF_NAME==bd_01ee_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_01ee_ila_lib_0 || ORIG_REF_NAME==bd_01ee_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/ip/ip_0/bd_01ee_ila_lib_0_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_0/bd_01ee_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_ref_design_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
