# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/bd_ref_design_LRX_0_0.xci
# IP: The module: 'bd_ref_design_LRX_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx3_Bank45/rx3_Bank45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx3_Bank45 || ORIG_REF_NAME==rx3_Bank45} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx1_Bank44/rx1_Bank44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx1_Bank44 || ORIG_REF_NAME==rx1_Bank44} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/Bank0_reg_map_iod/Bank0_reg_map_iod.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bank0_reg_map_iod || ORIG_REF_NAME==Bank0_reg_map_iod} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/LRX_reg_map/LRX_reg_map.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LRX_reg_map || ORIG_REF_NAME==LRX_reg_map} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx0_Bank25/rx0_Bank25.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx0_Bank25 || ORIG_REF_NAME==rx0_Bank25} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx2_Bank24/rx2_Bank24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx2_Bank24 || ORIG_REF_NAME==rx2_Bank24} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/fifo_generator_0_1/fifo_generator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0_1 || ORIG_REF_NAME==fifo_generator_0_1} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx3_Bank45/rx3_Bank45.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx3_Bank45 || ORIG_REF_NAME==rx3_Bank45} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx3_Bank45/rx3_Bank45_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx1_Bank44/rx1_Bank44.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx1_Bank44 || ORIG_REF_NAME==rx1_Bank44} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx1_Bank44/rx1_Bank44_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx0_Bank25/rx0_Bank25.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx0_Bank25 || ORIG_REF_NAME==rx0_Bank25} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx0_Bank25/rx0_Bank25_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx2_Bank24/rx2_Bank24.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx2_Bank24 || ORIG_REF_NAME==rx2_Bank24} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx2_Bank24/rx2_Bank24_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/fifo_generator_0_1/fifo_generator_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0_1 || ORIG_REF_NAME==fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/fifo_generator_0_1/fifo_generator_0_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0_1 || ORIG_REF_NAME==fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/LRX.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_LRX_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/bd_ref_design_LRX_0_0.xci
# IP: The module: 'bd_ref_design_LRX_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx3_Bank45/rx3_Bank45.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx3_Bank45 || ORIG_REF_NAME==rx3_Bank45} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx1_Bank44/rx1_Bank44.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx1_Bank44 || ORIG_REF_NAME==rx1_Bank44} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/Bank0_reg_map_iod/Bank0_reg_map_iod.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bank0_reg_map_iod || ORIG_REF_NAME==Bank0_reg_map_iod} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/LRX_reg_map/LRX_reg_map.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LRX_reg_map || ORIG_REF_NAME==LRX_reg_map} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx0_Bank25/rx0_Bank25.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx0_Bank25 || ORIG_REF_NAME==rx0_Bank25} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx2_Bank24/rx2_Bank24.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx2_Bank24 || ORIG_REF_NAME==rx2_Bank24} -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/fifo_generator_0_1/fifo_generator_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0_1 || ORIG_REF_NAME==fifo_generator_0_1} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx3_Bank45/rx3_Bank45.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx3_Bank45 || ORIG_REF_NAME==rx3_Bank45} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx3_Bank45/rx3_Bank45_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx1_Bank44/rx1_Bank44.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx1_Bank44 || ORIG_REF_NAME==rx1_Bank44} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx1_Bank44/rx1_Bank44_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx0_Bank25/rx0_Bank25.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx0_Bank25 || ORIG_REF_NAME==rx0_Bank25} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx0_Bank25/rx0_Bank25_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx2_Bank24/rx2_Bank24.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx2_Bank24 || ORIG_REF_NAME==rx2_Bank24} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/rx2_Bank24/rx2_Bank24_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/fifo_generator_0_1/fifo_generator_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0_1 || ORIG_REF_NAME==fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/fifo_generator_0_1/fifo_generator_0_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0_1 || ORIG_REF_NAME==fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/src/LRX.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_LRX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
