-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (lin64) Build 6140274 Wed May 21 22:58:25 MDT 2025
-- Date        : Fri Jan  9 17:32:15 2026
-- Host        : PORT-BABIN-L running 64-bit Ubuntu 22.04.5 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/bd_ref_design_LRX_0_0_stub.vhdl
-- Design      : bd_ref_design_LRX_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcku060-ffva1517-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity bd_ref_design_LRX_0_0 is
  Port ( 
    riu_clk : in STD_LOGIC;
    sw_rst_riu : in STD_LOGIC_VECTOR ( 7 downto 0 );
    sw_rst_app : in STD_LOGIC_VECTOR ( 119 downto 0 );
    rx_clk_p : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_clk_n : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_data_p : in STD_LOGIC_VECTOR ( 47 downto 0 );
    rx_data_n : in STD_LOGIC_VECTOR ( 47 downto 0 );
    strobe_rx_p : in STD_LOGIC_VECTOR ( 3 downto 0 );
    strobe_rx_n : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_sync : out STD_LOGIC;
    busA_strb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    busB_strb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    busC_strb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    busD_strb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    busA_valid : out STD_LOGIC;
    busB_valid : out STD_LOGIC;
    busC_valid : out STD_LOGIC;
    busD_valid : out STD_LOGIC;
    busA_sample0 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busA_sample1 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busA_sample2 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busA_sample3 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busA_sample4 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busA_sample5 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busA_sample6 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busA_sample7 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample0 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample1 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample2 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample3 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample4 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample5 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample6 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busB_sample7 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample0 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample1 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample2 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample3 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample4 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample5 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample6 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busC_sample7 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample0 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample1 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample2 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample3 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample4 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample5 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample6 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    busD_sample7 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    rx_rst_done : out STD_LOGIC;
    app_clk : out STD_LOGIC;
    s_axi_clk : in STD_LOGIC;
    s_axi_rst_n : in STD_LOGIC;
    s_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_arvalid : in STD_LOGIC;
    s_axi_arready : out STD_LOGIC;
    s_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_awvalid : in STD_LOGIC;
    s_axi_awready : out STD_LOGIC;
    s_axi_rready : in STD_LOGIC;
    s_axi_rvalid : out STD_LOGIC;
    s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_wvalid : in STD_LOGIC;
    s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_wready : out STD_LOGIC;
    s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_bready : in STD_LOGIC;
    s_axi_bvalid : out STD_LOGIC;
    s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busA_s_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busA_s_axi_arvalid : in STD_LOGIC;
    busA_s_axi_arready : out STD_LOGIC;
    busA_s_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busA_s_axi_awvalid : in STD_LOGIC;
    busA_s_axi_awready : out STD_LOGIC;
    busA_s_axi_rready : in STD_LOGIC;
    busA_s_axi_rvalid : out STD_LOGIC;
    busA_s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    busA_s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busA_s_axi_wvalid : in STD_LOGIC;
    busA_s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busA_s_axi_wready : out STD_LOGIC;
    busA_s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    busA_s_axi_bready : in STD_LOGIC;
    busA_s_axi_bvalid : out STD_LOGIC;
    busA_s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busB_s_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busB_s_axi_arvalid : in STD_LOGIC;
    busB_s_axi_arready : out STD_LOGIC;
    busB_s_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busB_s_axi_awvalid : in STD_LOGIC;
    busB_s_axi_awready : out STD_LOGIC;
    busB_s_axi_rready : in STD_LOGIC;
    busB_s_axi_rvalid : out STD_LOGIC;
    busB_s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    busB_s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busB_s_axi_wvalid : in STD_LOGIC;
    busB_s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busB_s_axi_wready : out STD_LOGIC;
    busB_s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    busB_s_axi_bready : in STD_LOGIC;
    busB_s_axi_bvalid : out STD_LOGIC;
    busB_s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busC_s_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busC_s_axi_arvalid : in STD_LOGIC;
    busC_s_axi_arready : out STD_LOGIC;
    busC_s_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busC_s_axi_awvalid : in STD_LOGIC;
    busC_s_axi_awready : out STD_LOGIC;
    busC_s_axi_rready : in STD_LOGIC;
    busC_s_axi_rvalid : out STD_LOGIC;
    busC_s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    busC_s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busC_s_axi_wvalid : in STD_LOGIC;
    busC_s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busC_s_axi_wready : out STD_LOGIC;
    busC_s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    busC_s_axi_bready : in STD_LOGIC;
    busC_s_axi_bvalid : out STD_LOGIC;
    busC_s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busD_s_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busD_s_axi_arvalid : in STD_LOGIC;
    busD_s_axi_arready : out STD_LOGIC;
    busD_s_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busD_s_axi_awvalid : in STD_LOGIC;
    busD_s_axi_awready : out STD_LOGIC;
    busD_s_axi_rready : in STD_LOGIC;
    busD_s_axi_rvalid : out STD_LOGIC;
    busD_s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    busD_s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    busD_s_axi_wvalid : in STD_LOGIC;
    busD_s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    busD_s_axi_wready : out STD_LOGIC;
    busD_s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    busD_s_axi_bready : in STD_LOGIC;
    busD_s_axi_bvalid : out STD_LOGIC;
    busD_s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of bd_ref_design_LRX_0_0 : entity is "bd_ref_design_LRX_0_0,LRX,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of bd_ref_design_LRX_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of bd_ref_design_LRX_0_0 : entity is "package_project";
end bd_ref_design_LRX_0_0;

architecture stub of bd_ref_design_LRX_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "riu_clk,sw_rst_riu[7:0],sw_rst_app[119:0],rx_clk_p[3:0],rx_clk_n[3:0],rx_data_p[47:0],rx_data_n[47:0],strobe_rx_p[3:0],strobe_rx_n[3:0],rx_sync,busA_strb[7:0],busB_strb[7:0],busC_strb[7:0],busD_strb[7:0],busA_valid,busB_valid,busC_valid,busD_valid,busA_sample0[11:0],busA_sample1[11:0],busA_sample2[11:0],busA_sample3[11:0],busA_sample4[11:0],busA_sample5[11:0],busA_sample6[11:0],busA_sample7[11:0],busB_sample0[11:0],busB_sample1[11:0],busB_sample2[11:0],busB_sample3[11:0],busB_sample4[11:0],busB_sample5[11:0],busB_sample6[11:0],busB_sample7[11:0],busC_sample0[11:0],busC_sample1[11:0],busC_sample2[11:0],busC_sample3[11:0],busC_sample4[11:0],busC_sample5[11:0],busC_sample6[11:0],busC_sample7[11:0],busD_sample0[11:0],busD_sample1[11:0],busD_sample2[11:0],busD_sample3[11:0],busD_sample4[11:0],busD_sample5[11:0],busD_sample6[11:0],busD_sample7[11:0],rx_rst_done,app_clk,s_axi_clk,s_axi_rst_n,s_axi_araddr[31:0],s_axi_arvalid,s_axi_arready,s_axi_awaddr[31:0],s_axi_awvalid,s_axi_awready,s_axi_rready,s_axi_rvalid,s_axi_rdata[31:0],s_axi_rresp[1:0],s_axi_wvalid,s_axi_wdata[31:0],s_axi_wready,s_axi_wstrb[3:0],s_axi_bready,s_axi_bvalid,s_axi_bresp[1:0],busA_s_axi_araddr[31:0],busA_s_axi_arvalid,busA_s_axi_arready,busA_s_axi_awaddr[31:0],busA_s_axi_awvalid,busA_s_axi_awready,busA_s_axi_rready,busA_s_axi_rvalid,busA_s_axi_rdata[31:0],busA_s_axi_rresp[1:0],busA_s_axi_wvalid,busA_s_axi_wdata[31:0],busA_s_axi_wready,busA_s_axi_wstrb[3:0],busA_s_axi_bready,busA_s_axi_bvalid,busA_s_axi_bresp[1:0],busB_s_axi_araddr[31:0],busB_s_axi_arvalid,busB_s_axi_arready,busB_s_axi_awaddr[31:0],busB_s_axi_awvalid,busB_s_axi_awready,busB_s_axi_rready,busB_s_axi_rvalid,busB_s_axi_rdata[31:0],busB_s_axi_rresp[1:0],busB_s_axi_wvalid,busB_s_axi_wdata[31:0],busB_s_axi_wready,busB_s_axi_wstrb[3:0],busB_s_axi_bready,busB_s_axi_bvalid,busB_s_axi_bresp[1:0],busC_s_axi_araddr[31:0],busC_s_axi_arvalid,busC_s_axi_arready,busC_s_axi_awaddr[31:0],busC_s_axi_awvalid,busC_s_axi_awready,busC_s_axi_rready,busC_s_axi_rvalid,busC_s_axi_rdata[31:0],busC_s_axi_rresp[1:0],busC_s_axi_wvalid,busC_s_axi_wdata[31:0],busC_s_axi_wready,busC_s_axi_wstrb[3:0],busC_s_axi_bready,busC_s_axi_bvalid,busC_s_axi_bresp[1:0],busD_s_axi_araddr[31:0],busD_s_axi_arvalid,busD_s_axi_arready,busD_s_axi_awaddr[31:0],busD_s_axi_awvalid,busD_s_axi_awready,busD_s_axi_rready,busD_s_axi_rvalid,busD_s_axi_rdata[31:0],busD_s_axi_rresp[1:0],busD_s_axi_wvalid,busD_s_axi_wdata[31:0],busD_s_axi_wready,busD_s_axi_wstrb[3:0],busD_s_axi_bready,busD_s_axi_bvalid,busD_s_axi_bresp[1:0]";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of riu_clk : signal is "xilinx.com:signal:clock:1.0 riu_clk CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of riu_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of riu_clk : signal is "XIL_INTERFACENAME riu_clk, ASSOCIATED_BUSIF sw_rst_riu, ASSOCIATED_RESET sw_rst_riu, FREQ_HZ 200000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_ref_design_clock_manager_0_0_riu_clk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of sw_rst_riu : signal is "xilinx.com:signal:reset:1.0 sw_rst_riu RST";
  attribute X_INTERFACE_MODE of sw_rst_riu : signal is "slave";
  attribute X_INTERFACE_PARAMETER of sw_rst_riu : signal is "XIL_INTERFACENAME sw_rst_riu, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rx_clk_p : signal is "xilinx.com:signal:clock:1.0 rx_clk_p CLK";
  attribute X_INTERFACE_MODE of rx_clk_p : signal is "slave";
  attribute X_INTERFACE_PARAMETER of rx_clk_p : signal is "XIL_INTERFACENAME rx_clk_p, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rx_clk_n : signal is "xilinx.com:signal:clock:1.0 rx_clk_n CLK";
  attribute X_INTERFACE_MODE of rx_clk_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of rx_clk_n : signal is "XIL_INTERFACENAME rx_clk_n, ASSOCIATED_RESET s_axi_rst_n, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of busA_strb : signal is "ti.com:user:adc_bus:1.0 adc_busA strobe";
  attribute X_INTERFACE_MODE of busA_strb : signal is "master";
  attribute X_INTERFACE_INFO of busB_strb : signal is "ti.com:user:adc_bus:1.0 adc_busB strobe";
  attribute X_INTERFACE_MODE of busB_strb : signal is "master";
  attribute X_INTERFACE_INFO of busC_strb : signal is "ti.com:user:adc_bus:1.0 adc_busC strobe";
  attribute X_INTERFACE_MODE of busC_strb : signal is "master";
  attribute X_INTERFACE_INFO of busD_strb : signal is "ti.com:user:adc_bus:1.0 adc_busD strobe";
  attribute X_INTERFACE_MODE of busD_strb : signal is "master";
  attribute X_INTERFACE_INFO of busA_valid : signal is "ti.com:user:adc_bus:1.0 adc_busA valid";
  attribute X_INTERFACE_INFO of busB_valid : signal is "ti.com:user:adc_bus:1.0 adc_busB valid";
  attribute X_INTERFACE_INFO of busC_valid : signal is "ti.com:user:adc_bus:1.0 adc_busC valid";
  attribute X_INTERFACE_INFO of busD_valid : signal is "ti.com:user:adc_bus:1.0 adc_busD valid";
  attribute X_INTERFACE_INFO of busA_sample0 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample0";
  attribute X_INTERFACE_INFO of busA_sample1 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample1";
  attribute X_INTERFACE_INFO of busA_sample2 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample2";
  attribute X_INTERFACE_INFO of busA_sample3 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample3";
  attribute X_INTERFACE_INFO of busA_sample4 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample4";
  attribute X_INTERFACE_INFO of busA_sample5 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample5";
  attribute X_INTERFACE_INFO of busA_sample6 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample6";
  attribute X_INTERFACE_INFO of busA_sample7 : signal is "ti.com:user:adc_bus:1.0 adc_busA sample7";
  attribute X_INTERFACE_INFO of busB_sample0 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample0";
  attribute X_INTERFACE_INFO of busB_sample1 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample1";
  attribute X_INTERFACE_INFO of busB_sample2 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample2";
  attribute X_INTERFACE_INFO of busB_sample3 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample3";
  attribute X_INTERFACE_INFO of busB_sample4 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample4";
  attribute X_INTERFACE_INFO of busB_sample5 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample5";
  attribute X_INTERFACE_INFO of busB_sample6 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample6";
  attribute X_INTERFACE_INFO of busB_sample7 : signal is "ti.com:user:adc_bus:1.0 adc_busB sample7";
  attribute X_INTERFACE_INFO of busC_sample0 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample0";
  attribute X_INTERFACE_INFO of busC_sample1 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample1";
  attribute X_INTERFACE_INFO of busC_sample2 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample2";
  attribute X_INTERFACE_INFO of busC_sample3 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample3";
  attribute X_INTERFACE_INFO of busC_sample4 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample4";
  attribute X_INTERFACE_INFO of busC_sample5 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample5";
  attribute X_INTERFACE_INFO of busC_sample6 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample6";
  attribute X_INTERFACE_INFO of busC_sample7 : signal is "ti.com:user:adc_bus:1.0 adc_busC sample7";
  attribute X_INTERFACE_INFO of busD_sample0 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample0";
  attribute X_INTERFACE_INFO of busD_sample1 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample1";
  attribute X_INTERFACE_INFO of busD_sample2 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample2";
  attribute X_INTERFACE_INFO of busD_sample3 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample3";
  attribute X_INTERFACE_INFO of busD_sample4 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample4";
  attribute X_INTERFACE_INFO of busD_sample5 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample5";
  attribute X_INTERFACE_INFO of busD_sample6 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample6";
  attribute X_INTERFACE_INFO of busD_sample7 : signal is "ti.com:user:adc_bus:1.0 adc_busD sample7";
  attribute X_INTERFACE_INFO of app_clk : signal is "xilinx.com:signal:clock:1.0 app_clk CLK";
  attribute X_INTERFACE_MODE of app_clk : signal is "master";
  attribute X_INTERFACE_PARAMETER of app_clk : signal is "XIL_INTERFACENAME app_clk, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_ref_design_LRX_0_0_app_clk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_clk : signal is "xilinx.com:signal:clock:1.0 s_axi_clk CLK";
  attribute X_INTERFACE_MODE of s_axi_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_clk : signal is "XIL_INTERFACENAME s_axi_clk, ASSOCIATED_BUSIF s_axi:busA_iod_s_axi:busB_iod_s_axi:busC_iod_s_axi:busD_iod_s_axi, FREQ_HZ 200000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_ref_design_clock_manager_0_0_riu_clk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_rst_n : signal is "xilinx.com:signal:reset:1.0 s_axi_rst_n RST";
  attribute X_INTERFACE_MODE of s_axi_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_rst_n : signal is "XIL_INTERFACENAME s_axi_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 s_axi ARADDR";
  attribute X_INTERFACE_MODE of s_axi_araddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_araddr : signal is "XIL_INTERFACENAME s_axi, ASSOCIATED_CLOCK s_axi_clk, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 200000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_ref_design_clock_manager_0_0_riu_clk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi ARVALID";
  attribute X_INTERFACE_INFO of s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 s_axi ARREADY";
  attribute X_INTERFACE_INFO of s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 s_axi AWADDR";
  attribute X_INTERFACE_INFO of s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi AWVALID";
  attribute X_INTERFACE_INFO of s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 s_axi AWREADY";
  attribute X_INTERFACE_INFO of s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 s_axi RREADY";
  attribute X_INTERFACE_INFO of s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi RVALID";
  attribute X_INTERFACE_INFO of s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 s_axi RDATA";
  attribute X_INTERFACE_INFO of s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 s_axi RRESP";
  attribute X_INTERFACE_INFO of s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi WVALID";
  attribute X_INTERFACE_INFO of s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 s_axi WDATA";
  attribute X_INTERFACE_INFO of s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 s_axi WREADY";
  attribute X_INTERFACE_INFO of s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 s_axi WSTRB";
  attribute X_INTERFACE_INFO of s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 s_axi BREADY";
  attribute X_INTERFACE_INFO of s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi BVALID";
  attribute X_INTERFACE_INFO of s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 s_axi BRESP";
  attribute X_INTERFACE_INFO of busA_s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi ARADDR";
  attribute X_INTERFACE_MODE of busA_s_axi_araddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of busA_s_axi_araddr : signal is "XIL_INTERFACENAME busA_iod_s_axi, ASSOCIATED_CLOCK s_axi_clk, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 200000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_ref_design_clock_manager_0_0_riu_clk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of busA_s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi ARVALID";
  attribute X_INTERFACE_INFO of busA_s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi ARREADY";
  attribute X_INTERFACE_INFO of busA_s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi AWADDR";
  attribute X_INTERFACE_INFO of busA_s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi AWVALID";
  attribute X_INTERFACE_INFO of busA_s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi AWREADY";
  attribute X_INTERFACE_INFO of busA_s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi RREADY";
  attribute X_INTERFACE_INFO of busA_s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi RVALID";
  attribute X_INTERFACE_INFO of busA_s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi RDATA";
  attribute X_INTERFACE_INFO of busA_s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi RRESP";
  attribute X_INTERFACE_INFO of busA_s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi WVALID";
  attribute X_INTERFACE_INFO of busA_s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi WDATA";
  attribute X_INTERFACE_INFO of busA_s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi WREADY";
  attribute X_INTERFACE_INFO of busA_s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi WSTRB";
  attribute X_INTERFACE_INFO of busA_s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi BREADY";
  attribute X_INTERFACE_INFO of busA_s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi BVALID";
  attribute X_INTERFACE_INFO of busA_s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 busA_iod_s_axi BRESP";
  attribute X_INTERFACE_INFO of busB_s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi ARADDR";
  attribute X_INTERFACE_MODE of busB_s_axi_araddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of busB_s_axi_araddr : signal is "XIL_INTERFACENAME busB_iod_s_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 200000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_ref_design_clock_manager_0_0_riu_clk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of busB_s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi ARVALID";
  attribute X_INTERFACE_INFO of busB_s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi ARREADY";
  attribute X_INTERFACE_INFO of busB_s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi AWADDR";
  attribute X_INTERFACE_INFO of busB_s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi AWVALID";
  attribute X_INTERFACE_INFO of busB_s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi AWREADY";
  attribute X_INTERFACE_INFO of busB_s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi RREADY";
  attribute X_INTERFACE_INFO of busB_s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi RVALID";
  attribute X_INTERFACE_INFO of busB_s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi RDATA";
  attribute X_INTERFACE_INFO of busB_s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi RRESP";
  attribute X_INTERFACE_INFO of busB_s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi WVALID";
  attribute X_INTERFACE_INFO of busB_s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi WDATA";
  attribute X_INTERFACE_INFO of busB_s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi WREADY";
  attribute X_INTERFACE_INFO of busB_s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi WSTRB";
  attribute X_INTERFACE_INFO of busB_s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi BREADY";
  attribute X_INTERFACE_INFO of busB_s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi BVALID";
  attribute X_INTERFACE_INFO of busB_s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 busB_iod_s_axi BRESP";
  attribute X_INTERFACE_INFO of busC_s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi ARADDR";
  attribute X_INTERFACE_MODE of busC_s_axi_araddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of busC_s_axi_araddr : signal is "XIL_INTERFACENAME busC_iod_s_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 200000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_ref_design_clock_manager_0_0_riu_clk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of busC_s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi ARVALID";
  attribute X_INTERFACE_INFO of busC_s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi ARREADY";
  attribute X_INTERFACE_INFO of busC_s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi AWADDR";
  attribute X_INTERFACE_INFO of busC_s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi AWVALID";
  attribute X_INTERFACE_INFO of busC_s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi AWREADY";
  attribute X_INTERFACE_INFO of busC_s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi RREADY";
  attribute X_INTERFACE_INFO of busC_s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi RVALID";
  attribute X_INTERFACE_INFO of busC_s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi RDATA";
  attribute X_INTERFACE_INFO of busC_s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi RRESP";
  attribute X_INTERFACE_INFO of busC_s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi WVALID";
  attribute X_INTERFACE_INFO of busC_s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi WDATA";
  attribute X_INTERFACE_INFO of busC_s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi WREADY";
  attribute X_INTERFACE_INFO of busC_s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi WSTRB";
  attribute X_INTERFACE_INFO of busC_s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi BREADY";
  attribute X_INTERFACE_INFO of busC_s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi BVALID";
  attribute X_INTERFACE_INFO of busC_s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 busC_iod_s_axi BRESP";
  attribute X_INTERFACE_INFO of busD_s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi ARADDR";
  attribute X_INTERFACE_MODE of busD_s_axi_araddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of busD_s_axi_araddr : signal is "XIL_INTERFACENAME busD_iod_s_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 200000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_ref_design_clock_manager_0_0_riu_clk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of busD_s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi ARVALID";
  attribute X_INTERFACE_INFO of busD_s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi ARREADY";
  attribute X_INTERFACE_INFO of busD_s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi AWADDR";
  attribute X_INTERFACE_INFO of busD_s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi AWVALID";
  attribute X_INTERFACE_INFO of busD_s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi AWREADY";
  attribute X_INTERFACE_INFO of busD_s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi RREADY";
  attribute X_INTERFACE_INFO of busD_s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi RVALID";
  attribute X_INTERFACE_INFO of busD_s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi RDATA";
  attribute X_INTERFACE_INFO of busD_s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi RRESP";
  attribute X_INTERFACE_INFO of busD_s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi WVALID";
  attribute X_INTERFACE_INFO of busD_s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi WDATA";
  attribute X_INTERFACE_INFO of busD_s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi WREADY";
  attribute X_INTERFACE_INFO of busD_s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi WSTRB";
  attribute X_INTERFACE_INFO of busD_s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi BREADY";
  attribute X_INTERFACE_INFO of busD_s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi BVALID";
  attribute X_INTERFACE_INFO of busD_s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 busD_iod_s_axi BRESP";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "LRX,Vivado 2025.1";
begin
end;
