set_property SRC_FILE_INFO {cfile:/home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_axi_interconnect_0_imp_auto_pc_0/bd_ref_design_axi_interconnect_0_imp_auto_pc_0_ooc.xdc rfile:../../../../../adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_axi_interconnect_0_imp_auto_pc_0/bd_ref_design_axi_interconnect_0_imp_auto_pc_0_ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.runs/bd_ref_design_axi_interconnect_0_imp_auto_pc_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 5.000 -name aclk [get_ports aclk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
