# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/DAC_DEMO/dac_demo_vivado_proj/dac_demo_design.srcs/sources_1/bd/design_1/ip/design_1_ltx_bus_0_0_0_1/design_1_ltx_bus_0_0_0.xci
# IP: The module: 'design_1_ltx_bus_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/DAC_DEMO/dac_demo_vivado_proj/dac_demo_design.srcs/sources_1/ip/high_speed_selectio_wiz_0/high_speed_selectio_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==high_speed_selectio_wiz_0 || ORIG_REF_NAME==high_speed_selectio_wiz_0} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/DAC_DEMO/dac_demo_vivado_proj/dac_demo_design.gen/sources_1/bd/design_1/ip/design_1_ltx_bus_0_0_0_1/design_1_ltx_bus_0_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ltx_bus_0_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/DAC_DEMO/dac_demo_vivado_proj/dac_demo_design.srcs/sources_1/bd/design_1/ip/design_1_ltx_bus_0_0_0_1/design_1_ltx_bus_0_0_0.xci
# IP: The module: 'design_1_ltx_bus_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/DAC_DEMO/dac_demo_vivado_proj/dac_demo_design.srcs/sources_1/ip/high_speed_selectio_wiz_0/high_speed_selectio_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==high_speed_selectio_wiz_0 || ORIG_REF_NAME==high_speed_selectio_wiz_0} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/DAC_DEMO/dac_demo_vivado_proj/dac_demo_design.gen/sources_1/bd/design_1/ip/design_1_ltx_bus_0_0_0_1/design_1_ltx_bus_0_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ltx_bus_0_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
