# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/adc_rx_xcku060.xdc

# Block Designs: bd/bd_ref_design/bd_ref_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design || ORIG_REF_NAME==bd_ref_design} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_util_vector_logic_0_0/bd_ref_design_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_util_vector_logic_0_0 || ORIG_REF_NAME==bd_ref_design_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_dummy_adc_data_capture_0_0/bd_ref_design_dummy_adc_data_capture_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_dummy_adc_data_capture_0_0 || ORIG_REF_NAME==bd_ref_design_dummy_adc_data_capture_0_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_jtag_axi_0_0/bd_ref_design_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_jtag_axi_0_0 || ORIG_REF_NAME==bd_ref_design_jtag_axi_0_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_util_vector_logic_1_0/bd_ref_design_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_util_vector_logic_1_0 || ORIG_REF_NAME==bd_ref_design_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/bd_ref_design_clock_manager_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_clock_manager_0_0 || ORIG_REF_NAME==bd_ref_design_clock_manager_0_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_LRX_0_0/bd_ref_design_LRX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_LRX_0_0 || ORIG_REF_NAME==bd_ref_design_LRX_0_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_axi_interconnect_0_imp_xbar_0/bd_ref_design_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==bd_ref_design_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_axi_interconnect_0_imp_auto_pc_0/bd_ref_design_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==bd_ref_design_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_axi_interconnect_0_0/bd_ref_design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_axi_interconnect_0_0 || ORIG_REF_NAME==bd_ref_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/bd_ref_design/ip/bd_ref_design_system_ila_0_0/bd_ref_design_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ref_design_system_ila_0_0 || ORIG_REF_NAME==bd_ref_design_system_ila_0_0} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/bd_ref_design_ooc.xdc
