# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_jtag_axi_0_0/bd_ref_design_jtag_axi_0_0.xci
# IP: The module: 'bd_ref_design_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_jtag_axi_0_0/bd_ref_design_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_jtag_axi_0_0/bd_ref_design_jtag_axi_0_0.xci
# IP: The module: 'bd_ref_design_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_jtag_axi_0_0/bd_ref_design_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
