#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 13 14:11:03 CEST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim design_1_wrapper_tb_func_synth -key {Post-Synthesis:sim_1:Functional:design_1_wrapper_tb} -tclbatch design_1_wrapper_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim design_1_wrapper_tb_func_synth -key {Post-Synthesis:sim_1:Functional:design_1_wrapper_tb} -tclbatch design_1_wrapper_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

