# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/bd_ref_design_clock_manager_0_0.xci
# IP: The module: 'bd_ref_design_clock_manager_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/mmcm_1/mmcm_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm_1 || ORIG_REF_NAME==mmcm_1} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/mmcm_1/mmcm_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm_1 || ORIG_REF_NAME==mmcm_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/mmcm_1/mmcm_1_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/clk_man_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_clock_manager_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.srcs/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/bd_ref_design_clock_manager_0_0.xci
# IP: The module: 'bd_ref_design_clock_manager_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/mmcm_1/mmcm_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm_1 || ORIG_REF_NAME==mmcm_1} -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/mmcm_1/mmcm_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm_1 || ORIG_REF_NAME==mmcm_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/mmcm_1/mmcm_1_ooc.xdc

# XDC: /home/deos/hu.babin-riby/Documents/Code/TSW_ADC_DAC_PROCESSING/ADC_DEMO/project/adc_ref_design.gen/sources_1/bd/bd_ref_design/ip/bd_ref_design_clock_manager_0_0/src/clk_man_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ref_design_clock_manager_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
